version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: retail_stock_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - retailstock-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: pnpm run dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - retailstock-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    command: pnpm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/retail_stock_db
      - JWT_SECRET=supersecretjwtkeythatshouldbeverylongandrandom
    depends_on:
      - postgres
    networks:
      - retailstock-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - retailstock-network

networks:
  retailstock-network:
    driver: bridge

volumes:
  postgres_data:
  frontend_node_modules:
